<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Web\config.html" />
    <EmbeddedResource Include="Web\config.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Data" Version="10.*-*" />
    <PackageReference Include="Jellyfin.Controller" Version="10.*-*" />
    <PackageReference Include="LiteDB" Version="5.0.15" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
